import { Router, type IRouter } from "express";
import healthRouter from "./health";
import studiosRouter from "./studios";
import classesRouter from "./classes";
import bookingsRouter from "./bookings";
import feedRouter from "./feed";
import forumRouter from "./forum";
import productsRouter from "./products";
import authRouter from "./auth";
import uploadsRouter from "./uploads";
import paymentsRouter from "./payments";
import messagesRouter from "./messages";
import reviewsRouter from "./reviews";
import wearablesRouter from "./wearables";
import ordersRouter from "./orders";
import challengesRouter from "./challenges";
import circlesRouter from "./circles";
import badgesRouter from "./badges";
import leaderboardRouter from "./leaderboard";
import calorieDataRouter from "./calorie-data";
import coachesRouter from "./coaches";
import brandsRouter from "./brands";

const router: IRouter = Router();

router.use(healthRouter);
router.use(studiosRouter);
router.use(classesRouter);
router.use(bookingsRouter);
router.use(feedRouter);
router.use(forumRouter);
router.use(productsRouter);
router.use(authRouter);
router.use("/uploads", uploadsRouter);
router.use("/payments", paymentsRouter);
router.use(messagesRouter);
router.use(reviewsRouter);
router.use(wearablesRouter);
router.use(ordersRouter);
router.use(challengesRouter);
router.use(circlesRouter);
router.use(badgesRouter);
router.use(leaderboardRouter);
router.use(calorieDataRouter);
router.use(coachesRouter);
router.use(brandsRouter);

export default router;
